### ISSUE TITLE
forward_reverse 

### ISSUE THREAD

**Issue by mcieslik-mctp** [shenkers/isoscm#13]
Really nice work, thanks a lot for making this tool.

I am using it on STAR aligned files, due to a peculiarity of STAR in the reporting of chimeric reads it is better to swap the reads in a "reverse_forward" library  i.e. making it a "forward_reverse" library.

Would it be possible to add "forward_reverse" as an option? Otherwise I would have to re-align or somehow re-code alignments for 1000s of samples.

Thanks!

**Comment by shenkers** [comment]
Thanks for your compliment!

This would be technically possible to add, my only concern is that I don't think that any sequencing platforms generate reads with a  "forward_reverse" orientation, so adding such an option may create confusion. 

I anticipate that I will have to change the code in a few different places, I'll try to get to this in the next couple days. 

If you decide you want to go the route of re-coding the pair-order information, it would be quite straightforward to do. Using HTSJDK it would look something like this:

``` java
File inBam = new File("in.bam");
File outBam = new File("out.bam");

SAMFileReader sfr = new SAMFileReader(inBam);

// create a bam file writer
SAMFileWriterFactory sfwf = new SAMFileWriterFactory();
boolean presorted = sfr.getFileHeader().getSortOrder() != SortOrder.unsorted;
SAMFileWriter sfw = sfwf.makeBAMWriter(sfr.getFileHeader(), presorted, outBam);

// for each read in the input swap the order of the mate pairs and add it to the output
SAMRecordIterator sri = sfr.iterator();

while(sri.hasNext()){
    SAMRecord sr = sri.next();
    sr.setFirstOfPairFlag(!sr.getFirstOfPairFlag());
    sfw.addAlignment(sr);
}

// close the input and output resources
sfr.close();
sfw.close();
```

**Comment by shenkers** [comment]
Hi @mcieslik-mctp, I think I've made the necessary changes to add this option. Would it be possible for you to share a sample of your data so that I can make sure things are running correctly before I upload a new version? If you you could use 

``` bash
samtools view -b file.bam chrABC:123-456 > out.bam
```

to select reads from some interval with a couple of expressed genes on the plus and minus strand that would be useful for me to check against. Thanks!
