### ISSUE TITLE
Genomic coordinates on -ve strand

### ISSUE THREAD

**Issue by qoiopipq** [shenkers/isoscm#15]
Here's a part of the output from compare step:
**changepoint**  confidence log_odds     **upstream_segment**   _downstream_segment_    locus   **strand**
**chr17:87992066-87992066**   9.96E-01  5.60E+00      **chr17:87992066-87992175**   _chr17:87990916-87992065_   chr17:87990916-87992175 **-**
**chr9:7206830-7206830**    4.88E-01    -4.75E-02   **chr9:7206720-7206830**    _chr9:7206831-7207032_  chr9:7206720-72070 **+**
(bold text: change point, upstream_segment and strand, italic: downstream_segment, sorry for the format)

I'm a bit confused by the genomic coordinates of upstream and downstream segments on -ve strand. My understanding is that the upstream segments have lower genomic coordinates (more toward 5' ends), while downstream segments have higher coordinates (more toward 3' ends). This still applies to polyA events that have been identified on +ve strand. However, on the -ve strand, the genomic coordinates of upstream segments are always higher than downstream segments (shown above). And also the locations of the change points are different between +ve and -ve strands in regard to the start sites of downstream segments.

Do you think this is reasonable that just swop the genomic coordinates between downstream_segment and upstream_segment on -ve strand? And also adjust the change point locations whenever they are on -ve strand?

Cheers!

**Comment by shenkers** [comment]
In this case upstream and downstream are relative to the reference frame of the gene. The upstream segment is closer to the 5'end of the gene, and the downstream segment is farther from the 5' end of the gene. The position of the changepoint will always be the 3'end of the upstream segment, and whether this is the start or end of that segment depends on whether the gene is on the +/- strand.

I've included a picture below to clarify where the segments are located relative to the changepoint for genes on +/- strands:
![changepoint_segments](https://cloud.githubusercontent.com/assets/2341961/12680485/264617e2-c678-11e5-8af2-0b605cf68524.png)

Let me know if this still isn't clear.

**Comment by qoiopipq** [comment]
Got it!
Thank you!

**Comment by qoiopipq** [comment]
I want to compare 3' UTRs between two tissue types. I did the assemble and compare steps on them. It ended up with 154/8,921 polyA events after several filtering steps:
- Confidence values >=0.99 (i.e P-values <=0.01) -> 1,895 polyA events
- Cutoff upstream coverage >=16.18: the lower median value between two tissue types -> 1,425 events
- |differential_usage| >=0.2: a bit arbitrarily -> 205 events
- Downstream segment length >=159: the lower 1st Qu. value between two samples -> 154 events

Then I visualized BAM (from Tophat) and GTF (from IsoSCM assemble) files in IGV. I checked 10 events that with high |differential_usage| values (>0.75): 2 of them perfectly match with the prediction, including locations of change points, up/down stream segments (from compare step); 2 of them have change points (and their coordinates) as predicted, but upstream/downstream segments are shifted a bit (sometimes a few kb) ; and 6 of them do not show any differences (in BAM or GTF files) between two samples around the predicted change points. 

I think IsoSCM is a very good tool for generating informative 3'UTR predictions even with the shifted upstream/downstream segments. But my concern is what can I do with those do not show any differences around the predicted change points? Obviously, we can't ignore or discard them, because most of them have very low p-values. Any suggestions?

Cheers

**Comment by shenkers** [comment]
It's difficult to tell what the issue is from your description alone. Could you please share some screenshots of the coverage and generated gene models that are incongruous (both shifted and no-difference cases)?

**Comment by qoiopipq** [comment]
I try my best to describe the two cases with screenshots. Let me know if it needs a bit more explanations.
- No-differencecase:
  1st panel: Thymus BAM file (black dash line indicates the predicted changepoint, range of read counts is 0-1200, same in Liver BAM file)
  2nd: Liver BAM file
  3rd: RefSeq of Atf5 gene
  4th: Thymus 3p exons (in blue)
  5th: Liver 3p exons (in green)
  ![atf5](https://cloud.githubusercontent.com/assets/16911467/12740342/6d3f96c2-c9c6-11e5-917f-7fbeb9e6d089.png)

Genomic coordinates in IGV the 4th and 5th panels (from top to the bottom):
the longest 3p exon in Thymus: chr7:44812550-44813520
3p exon in Thymus: chr7: 44812560-44813520
the shortest 3p exon in Thymus (the shortest exon in blue): chr7:44813080-44813520
the longest 3p exon in Liver: chr7:44812257-44813520
3p exon in Liver: chr7:44812267-44813520
the shortest 3p exon in Liver: chr7:44812547 - 44813520

While the predicted change point from compare step is chr7:44813047-44813047, upstream-seg:chr7:44813047-44813520, and downstream-seg: chr7:44812527-44813046
The change point and up/downstream locations do not match with any 3p exons in IGV.
- Shifted case:
  1st panel: Thymus BAM file (black dash line indicates the predicted changepoint, range of read counts is 0-200, same in Liver BAM file)
  2nd: Liver BAM file
  3rd: RefSeq of Rqcd1 gene
  4th: Thymus 3p exons (in blue)
  5th: Liver 3p exons (in green)
  ![rqcd1](https://cloud.githubusercontent.com/assets/16911467/12740902/010f2e6c-c9cc-11e5-9a06-84e44b043f5f.png)

Genomic coordinates in IGV the 4th and 5th panels (from top to the bottom):
the longest 3p exon in Thymus: chr1:74528686-74530169
3p exon in Thymus: chr1:74528686-**74530116**
the shortest 3p exon in Thymus: chr1:74528686-_74529216_
the longest 3p exon in Liver: chr1:74528686-74531120
3p exon in Liver: chr1:74528686-74530796
the shortest 3p exon in Liver: chr1:74528686-74528836

The predicted change point is chr1:_74529216-74529216_, upstream-seg:chr1:74528957-74529216 and downstream-seg is chr1:74529217-**74530116**

Change point location matches with the shortest 3p exon in thymus. But predicted downstream-seg matches with 3p exon in thymus not in liver. Is this because of the shifted prediction in Liver that I mentioned earlier, or the differences of 3' UTRs between thymus and liver are not as significant as the ones within thymus? I assume the aim of compare step is to compare 3' UTRs between samples.

Cheers

**Comment by shenkers** [comment]
Thanks for posting the pictures, I think I understand what you are saying. 

I think the source of confusion is that the change-points identified during the compare step are not necessarily the same as those identified during the 'assemble' step. When you run the 'assemble' step IsoSCM identifies changepoints in the 3'UTR using data from a single sample. When you run the 'compare' step, IsoSCM performs a 'joint' segmentation, which integrates the RNA-seq coverage pattern in both samples simultaneously when identifying changepoints. The change-points identified during this joint segmentation are not necessarily going to be the same as when segmenting each sample independently.

The change-points identified during the assemble step are estimates of the 3'end given a particular sample. If you had replicates of the same condition the estimated 3'end may differ slightly if you were to assemble them independently. By segmenting multiple segments together you get a single, more concise, set of changepoints that describe the coverage patterns in all the samples. I included a little cartoon showing the union of changepoints between to samples (which is what I think you were expecting to see in the 'compare' output), versus what the joint segmentation might produce.

![joint_changepoints](https://cloud.githubusercontent.com/assets/2341961/12753010/14aafbc4-c993-11e5-93f8-af1ea3133e2a.png)

Here, sample#1 and sample#2 are meant to show the changepoints (vertical lines) that would be identified when running the assemble command on each sample individually might be slightly different. If you were to take the union of these sets of changepoints the result might have very short segments that do not reflect real 3'ends. The last row is supposed to show that the compare command generates a single set of changepoints that reflects the coverage in both samples, but does not necessarily match the changepoints identified by the assemble command.

Let me know if I mis-understood your question.
