### ISSUE TITLE
Mapping with star - XS flag

### ISSUE THREAD

**Issue by adomingues** [shenkers/isoscm#9]
I have mapped alignments with STAR (stranded data, dUTP, PE101), that lack the XS flag. I guess that is reason why assembly step fails:

```
java -Xmx6g -jar ~/bin/IsoSCM-2.0.9.jar assemble -bam WT.bam -base WT -s reverse_forward
2015-06-23T12:44:03,657 [main] INFO  executable.IsoSCM - Starting assemble ...
2015-06-23T12:44:04,257 [main] INFO  executable.IsoSCM - tabulating splice junctions...
Exception in thread "main" java.lang.NullPointerException
        at processing.FindSpliceJunctions.tabulateSpliceJunctions(FindSpliceJunctions.java:144)
        at executable.IsoSCM.main(IsoSCM.java:221)
```

Is the lack of XS flag the issue? Have you tested isoscm with STAR alignments? 

Cheers.

**Comment by shenkers** [comment]
Yes,  absence of the XS flag would cause an error, although people have used STAR with IsoSCM before. I believe there is a flag you can set when using STAR to add the XS flag. This thread provides the details of how to do that:

http://seqanswers.com/forums/archive/index.php/t-30905.html

Let me know if you run into any more problems.

Best,
Sol

**Comment by cyrilcros** [comment]
The STAR manual has a compatibility with Cufflinks section:

> 4.2.3 Compatibility with Cufflinks Cuffdiff.
> For unstranded RNA-seq data, Cufflinks/Cuffdiff require spliced alignments with XS strand attribute,
> which STAR will generate with --outSAMstrandField intronMotif option. As required, the XS
> strand attribute will be generated for all alignments that contain splice junctions. The spliced
> alignments that have undened strand (i.e. containing only non-canonical unannotated junctions)
> will be suppressed.
> If you have stranded RNA-seq data, you do not need to use any specic STAR options. Instead,
> you need to run Cufflinks with the library option --library-type options.> For example, cufflinks
> ... --library-type fr-firststrand should be used for the standard dUTP protocol, including
> Illumina's stranded Tru-Seq. >This option has to be used only for Cufflinks runs and not for STAR
> runs.
> In addition, it is recommended to remove the non-canonical junctions for Cufflinks runs using
> --outFilterIntronMotifs RemoveNoncanonical.
